dataclean <- function(dat){
	source("scripts/outlier_function.R")
	source("scripts/co2calibration_function.R")
	
	co2.cal <- co2calibrate(dat$co2_1,dat$co2_2,dat$gs3_1_temp,
		dat$gs3_2_temp,dat$ctd1_depth,dat$ctd2_depth)
	co2.cal <- as.data.frame(co2.cal)
	
	dat$co2_1 <- co2.cal$co2_1
	dat$co2_2 <- co2.cal$co2_2
	
	dat <- mkrf.30
	mkrf.nov <- subset(dat, format(timestamp,'%m') %in% c("11"))
	mkrf.dec <- subset(dat, format(timestamp,'%m') %in% c("12"))
	mkrf.jan <- subset(dat, format(timestamp,'%m') %in% c("01"))
	mkrf.feb <- subset(dat, format(timestamp,'%m') %in% c("02"))
	mkrf.mar <- subset(dat, format(timestamp,'%m') %in% c("03"))
	mkrf.apr <- subset(dat, format(timestamp,'%m') %in% c("04"))
	mkrf.may <- subset(dat, format(timestamp,'%m') %in% c("05"))
	mkrf.jun <- subset(dat, format(timestamp,'%m') %in% c("06"))
	
	mkrf.nov$co2_1 <- outlier(mkrf.nov, co2_1)
	mkrf.nov$co2_2 <- outlier(mkrf.nov, co2_2)
	mkrf.nov$orp <- outlier(mkrf.nov, orp)
	mkrf.nov$ph1 <- outlier(mkrf.nov, ph1)
	mkrf.nov$ph2 <- outlier(mkrf.nov, ph2)
	mkrf.nov$gs3_1_temp <- outlier(mkrf.nov, gs3_1_temp)
	mkrf.nov$gs3_1_ec <- outlier(mkrf.nov, gs3_1_ec)
	mkrf.nov$gs3_2_ec <- outlier(mkrf.nov, gs3_2_ec)
	mkrf.nov$sonic_u <- outlier(mkrf.nov, sonic_u)
	mkrf.nov$sonic_v <- outlier(mkrf.nov, sonic_v)
	mkrf.nov$sonic_w <- outlier(mkrf.nov, sonic_w)
	mkrf.nov$sonic_temp <- outlier(mkrf.nov, sonic_temp)
	
	mkrf.dec$co2_1 <- outlier(mkrf.dec, co2_1)
	mkrf.dec$co2_2 <- outlier(mkrf.dec, co2_2)
	mkrf.dec$orp <- outlier(mkrf.dec, orp)
	mkrf.dec$ph1 <- outlier(mkrf.dec, ph1)
	mkrf.dec$ph2 <- outlier(mkrf.dec, ph2)
	mkrf.dec$gs3_1_temp <- outlier(mkrf.dec, gs3_1_temp)
	mkrf.dec$gs3_1_ec <- outlier(mkrf.dec, gs3_1_ec)
	mkrf.dec$gs3_2_ec <- outlier(mkrf.dec, gs3_2_ec)
	mkrf.dec$sonic_u <- outlier(mkrf.dec, sonic_u)
	mkrf.dec$sonic_v <- outlier(mkrf.dec, sonic_v)
	mkrf.dec$sonic_w <- outlier(mkrf.dec, sonic_w)
	mkrf.dec$sonic_temp <- outlier(mkrf.dec, sonic_temp)
	
	mkrf.jan$co2_1 <- outlier(mkrf.jan, co2_1)
	mkrf.jan$co2_2 <- outlier(mkrf.jan, co2_2)
	mkrf.jan$orp <- outlier(mkrf.jan, orp)
	mkrf.jan$ph1 <- outlier(mkrf.jan, ph1)
	mkrf.jan$ph2 <- outlier(mkrf.jan, ph2)
	mkrf.jan$gs3_1_temp <- outlier(mkrf.jan, gs3_1_temp)
	mkrf.jan$gs3_1_ec <- outlier(mkrf.jan, gs3_1_ec)
	mkrf.jan$gs3_2_ec <- outlier(mkrf.jan, gs3_2_ec)
	mkrf.jan$sonic_u <- outlier(mkrf.jan, sonic_u)
	mkrf.jan$sonic_v <- outlier(mkrf.jan, sonic_v)
	mkrf.jan$sonic_w <- outlier(mkrf.jan, sonic_w)
	mkrf.jan$sonic_temp <- outlier(mkrf.jan, sonic_temp)
	
	mkrf.feb$co2_1 <- outlier(mkrf.feb, co2_1)
	mkrf.feb$co2_2 <- outlier(mkrf.feb, co2_2)
	mkrf.feb$orp <- outlier(mkrf.feb, orp)
	mkrf.feb$ph1 <- outlier(mkrf.feb, ph1)
	mkrf.feb$ph2 <- outlier(mkrf.feb, ph2)
	mkrf.feb$gs3_1_temp <- outlier(mkrf.feb, gs3_1_temp)
	mkrf.feb$gs3_1_ec <- outlier(mkrf.feb, gs3_1_ec)
	mkrf.feb$gs3_2_ec <- outlier(mkrf.feb, gs3_2_ec)
	mkrf.feb$sonic_u <- outlier(mkrf.feb, sonic_u)
	mkrf.feb$sonic_v <- outlier(mkrf.feb, sonic_v)
	mkrf.feb$sonic_w <- outlier(mkrf.feb, sonic_w)
	mkrf.feb$sonic_temp <- outlier(mkrf.feb, sonic_temp)
	
	mkrf.mar$co2_1 <- outlier(mkrf.mar, co2_1)
	mkrf.mar$co2_2 <- outlier(mkrf.mar, co2_2)
	mkrf.mar$orp <- outlier(mkrf.mar, orp)
	mkrf.mar$ph1 <- outlier(mkrf.mar, ph1)
	mkrf.mar$ph2 <- outlier(mkrf.mar, ph2)
	mkrf.mar$gs3_1_temp <- outlier(mkrf.mar, gs3_1_temp)
	mkrf.mar$gs3_1_ec <- outlier(mkrf.mar, gs3_1_ec)
	mkrf.mar$gs3_2_ec <- outlier(mkrf.mar, gs3_2_ec)
	mkrf.mar$sonic_u <- outlier(mkrf.mar, sonic_u)
	mkrf.mar$sonic_v <- outlier(mkrf.mar, sonic_v)
	mkrf.mar$sonic_w <- outlier(mkrf.mar, sonic_w)
	mkrf.mar$sonic_temp <- outlier(mkrf.mar, sonic_temp)
	
	mkrf.apr$co2_1 <- outlier(mkrf.apr, co2_1)
	mkrf.apr$co2_2 <- outlier(mkrf.apr, co2_2)
	mkrf.apr$orp <- outlier(mkrf.apr, orp)
	mkrf.apr$ph1 <- outlier(mkrf.apr, ph1)
	mkrf.apr$ph2 <- outlier(mkrf.apr, ph2)
	mkrf.apr$gs3_1_temp <- outlier(mkrf.apr, gs3_1_temp)
	mkrf.apr$gs3_1_ec <- outlier(mkrf.apr, gs3_1_ec)
	mkrf.apr$gs3_2_ec <- outlier(mkrf.apr, gs3_2_ec)
	mkrf.apr$sonic_u <- outlier(mkrf.apr, sonic_u)
	mkrf.apr$sonic_v <- outlier(mkrf.apr, sonic_v)
	mkrf.apr$sonic_w <- outlier(mkrf.apr, sonic_w)
	mkrf.apr$sonic_temp <- outlier(mkrf.apr, sonic_temp)
	
	mkrf.may$co2_1 <- outlier(mkrf.may, co2_1)
	mkrf.may$co2_2 <- outlier(mkrf.may, co2_2)
	mkrf.may$orp <- outlier(mkrf.may, orp)
	mkrf.may$ph1 <- outlier(mkrf.may, ph1)
	mkrf.may$ph2 <- outlier(mkrf.may, ph2)
	mkrf.may$gs3_1_temp <- outlier(mkrf.may, gs3_1_temp)
	mkrf.may$gs3_1_ec <- outlier(mkrf.may, gs3_1_ec)
	mkrf.may$gs3_2_ec <- outlier(mkrf.may, gs3_2_ec)
	mkrf.may$sonic_u <- outlier(mkrf.may, sonic_u)
	mkrf.may$sonic_v <- outlier(mkrf.may, sonic_v)
	mkrf.may$sonic_w <- outlier(mkrf.may, sonic_w)
	mkrf.may$sonic_temp <- outlier(mkrf.may, sonic_temp)
	
	mkrf.jun$co2_1 <- outlier(mkrf.jun, co2_1)
	mkrf.jun$co2_2 <- outlier(mkrf.jun, co2_2)
	mkrf.jun$orp <- outlier(mkrf.jun, orp)
	mkrf.jun$ph1 <- outlier(mkrf.jun, ph1)
	mkrf.jun$ph2 <- outlier(mkrf.jun, ph2)
	mkrf.jun$gs3_1_temp <- outlier(mkrf.jun, gs3_1_temp)
	mkrf.jun$gs3_1_ec <- outlier(mkrf.jun, gs3_1_ec)
	mkrf.jun$gs3_2_ec <- outlier(mkrf.jun, gs3_2_ec)
	mkrf.jun$sonic_u <- outlier(mkrf.jun, sonic_u)
	mkrf.jun$sonic_v <- outlier(mkrf.jun, sonic_v)
	mkrf.jun$sonic_w <- outlier(mkrf.jun, sonic_w)
	mkrf.jun$sonic_temp <- outlier(mkrf.jun, sonic_temp)
	
	mkrf <- rbind(mkrf.nov, mkrf.dec, mkrf.jan, mkrf.feb, mkrf.mar, mkrf.apr, mkrf.may, mkrf.jun)
	return(mkrf)
}